'use client';

import { useEffect, useRef, useState } from 'react';

type Demo = { number: string; kind: string; title: string; question: string; answer: string; caption: string; audio: string; duration: string; sources: { name:string; x:number; y:number; tone:string }[]; transcript: { time:string; speaker:string; text:string }[]; relations:string[] };

const demos: Demo[] = [
  { number:'01', kind:'Single-node perception', title:'Locate one sound event.', question:'Which sound event occurs behind the listener?', answer:'Cough', caption:'On a rainy balcony, two friends chat while a violinist moves through the space. Bells and a cough punctuate the scene.', audio:'/audio/rainy-balcony.flac', duration:'00:29', sources:[{name:'Speaker A',x:27,y:31,tone:'speech'},{name:'Speaker B',x:73,y:35,tone:'speech'},{name:'Violin',x:17,y:52,tone:'music'},{name:'Jingle bell',x:73,y:61,tone:'event'},{name:'Cough',x:66,y:81,tone:'event'}], transcript:[{time:'00:00',speaker:'A',text:"Listen, someone's playing violin out here in the rain."},{time:'00:05',speaker:'B',text:"Yeah, it's beautiful. He's been walking toward the right side of the balcony."},{time:'00:22',speaker:'A',text:'Bless you! Are you cold out here?'}], relations:['Cough → Speaker A response','Speaker A → Speaker B reply'] },
  { number:'02', kind:'Single-relation reasoning', title:'What makes the dog bark?', question:'Which event directly causes the dog to bark?', answer:'Vacuum cleaner', caption:'In a spacious garage, two people talk as a vacuum cleaner moves across the floor and a dog barks nearby.', audio:'/audio/garage-vacuum.flac', duration:'00:13', sources:[{name:'Speaker A',x:71,y:30,tone:'speech'},{name:'Speaker B',x:78,y:70,tone:'speech'},{name:'Vacuum',x:61,y:80,tone:'event'},{name:'Dog',x:26,y:42,tone:'event'}], transcript:[{time:'00:00',speaker:'A',text:'Can you hear that from outside?'},{time:'00:04',speaker:'B',text:"It sounds like someone's cleaning the garage."},{time:'00:09',speaker:'—',text:'Vacuum cleaner rolls; dog barks.'}], relations:['Speaker B → Vacuum','Vacuum → Dog bark'] },
  { number:'03', kind:'Multi-relation reasoning', title:'Trace the causal chain.', question:'What sequence best explains the speaker’s comment about the fly?', answer:'Telephone rings → speaker responds → fly buzzes past', caption:'In a TV room, a telephone rings; someone comments as a housefly buzzes by, with a kettle whistling in the background.', audio:'/audio/tv-room.flac', duration:'00:13', sources:[{name:'Telephone',x:71,y:34,tone:'event'},{name:'Speaker',x:26,y:34,tone:'speech'},{name:'Housefly',x:35,y:58,tone:'event'},{name:'Kettle',x:72,y:77,tone:'event'}], transcript:[{time:'00:00',speaker:'—',text:'Telephone rings.'},{time:'00:03',speaker:'A',text:'Did you see that fly go by?'},{time:'00:10',speaker:'—',text:'A kettle begins to whistle.'}], relations:['Telephone → Speaker response','Speaker response → Housefly reference'] },
];
const wave = [18,39,23,57,31,69,42,26,52,73,31,48,24,66,40,78,36,19,49,65,28,53,35,71,45,25,58,33,67,47,21,56,38,76,29,51,35,63,25,45];

export default function Home() {
  const audioRef = useRef<HTMLAudioElement>(null); const [active,setActive]=useState(0); const [playing,setPlaying]=useState(false); const [progress,setProgress]=useState(0); const demo=demos[active];
  useEffect(()=>{ const audio=audioRef.current; if(audio){audio.pause();audio.currentTime=0;} setProgress(0);setPlaying(false);},[active]);
  const toggle=()=>{const audio=audioRef.current;if(!audio)return; audio.paused?audio.play():audio.pause();};
  return <main>
    <header className="siteHeader"><a className="brand" href="#top">Binaural<span>LALM</span></a><nav><a href="#dataset">Dataset</a><a href="#demos">Demos</a><a href="#paper">Paper</a></nav><a className="access" href="#paper">Private preview</a></header>
    <section className="hero" id="top"><p className="eyebrow">Spatially grounded audio-language dataset</p><h1>Hear the world<br/><i>in three dimensions.</i></h1><p className="heroCopy">BinauralLALM links audio, space, event relations, and language—so models can reason about what happened, where it happened, and why.</p><a className="heroButton" href="#demos">Explore the demos <span>↓</span></a><div className="heroStrip"><span>Binaural audio</span><span>Spatial scene graphs</span><span>Grounded language</span></div></section>
    <section className="intro" id="dataset"><div><p className="eyebrow">A dataset built for spatial reasoning</p><h2>One scene,<br/>multiple forms of evidence.</h2></div><p>Each sample combines a binaural mixture with source-level annotations, a spatial layout, temporal events, causal relations, and language grounded in the scene. The three demos below introduce the reasoning progression.</p></section>
    <section className="demos" id="demos"><div className="sectionLead"><p className="eyebrow">Interactive demonstrations</p><h2>Listen. Locate. Reason.</h2><p>These are showcase views, not annotation tasks. Playback and scene evidence are available, while validation controls are intentionally removed.</p></div>
      <div className="demoTabs" role="tablist">{demos.map((item,index)=><button key={item.number} role="tab" aria-selected={active===index} onClick={()=>setActive(index)}><small>{item.number}</small>{item.kind}</button>)}</div>
      <article className="demoShell"><div className="demoIntro"><p className="eyebrow">{demo.kind}</p><h3>{demo.title}</h3><p>{demo.caption}</p></div><div className="audioBar"><button className="playButton" onClick={toggle} aria-label={playing?'Pause audio':'Play audio'}>{playing?'Ⅱ':'▶'}</button><div className="waveform">{wave.map((height,index)=><i key={index} style={{height:`${height}%`,opacity:index/wave.length<progress?1:.35}}/>)}</div><span>{Math.round(progress*100).toString().padStart(2,'0')}% / {demo.duration}</span><audio ref={audioRef} src={demo.audio} preload="metadata" onPlay={()=>setPlaying(true)} onPause={()=>setPlaying(false)} onEnded={()=>{setPlaying(false);setProgress(0)}} onTimeUpdate={e=>setProgress(e.currentTarget.duration?e.currentTarget.currentTime/e.currentTarget.duration:0)}/></div>
      <div className="evidenceGrid"><section className="mapPanel"><div className="panelTitle">Spatial map <span>listener-centered</span></div><div className="spatialMap"><div className="cross horizontal"/><div className="cross vertical"/><span className="direction north">front</span><span className="direction south">rear</span><span className="direction east">right</span><span className="direction west">left</span><div className="listener">You</div>{demo.sources.map(source=><div className={`sourceDot ${source.tone}`} style={{left:`${source.x}%`,top:`${source.y}%`}} key={source.name}><b>{source.name}</b></div>)}</div></section>
      <section className="graphPanel"><div className="panelTitle">Scene graph <span>causal relations</span></div><div className="graph"><div className="graphLine lineOne"/><div className="graphLine lineTwo"/><div className="graphLine lineThree"/>{demo.sources.slice(0,4).map((s,i)=><div className={`graphNode n${i+1}`} key={s.name}>{s.name}</div>)}</div><div className="relationList">{demo.relations.map(relation=><span key={relation}>{relation}</span>)}</div></section>
      <section className="transcriptPanel"><div className="panelTitle">Transcription <span>time-aligned</span></div><div className="transcript">{demo.transcript.map(line=><p key={line.time}><time>{line.time}</time><b>{line.speaker}</b><span>{line.text}</span></p>)}</div></section>
      <section className="qaPanel"><div className="panelTitle">Grounded QA sample <span>read-only</span></div><p className="question">{demo.question}</p><div className="answer"><small>Recorded answer</small><strong>{demo.answer}</strong></div><p className="qaNote">The answer is shown together with its audible, spatial, and relational evidence.</p></section></div></article>
    </section>
    <section className="paper" id="paper"><p className="eyebrow">Paper overview</p><h2>Research details,<br/>coming next.</h2><div className="paperSlots"><div><span>01</span><b>Abstract & contribution</b><small>Reserved for paper summary</small></div><div><span>02</span><b>Method</b><small>Reserved for pipeline figure</small></div><div><span>03</span><b>Experiments & analysis</b><small>Reserved for results and findings</small></div></div></section>
    <footer><span>BinauralLALM · Private research preview</span><span>KAIST · 2026</span></footer>
  </main>;
}
